storage_impl: "database"
logger:
  level: "INFO"
database:
  host: "172.20.10.4"
  port: 5430
  schema: "calendar"
  database_db: "postgres_db"
  user: "postgres_user"
  password: "postgres_password"

